document.writeln("	<div class=\'footer text-white\'>");
document.writeln("  		<div class=\'footNav\'>");
document.writeln("  			<ul class=\'clearfix\'>");
document.writeln("	  			<li class=\'pos-r\'>");
document.writeln("	  				<a href=\'index.html\'>HOME</a>");
document.writeln("	  				<div class=\'second\'>");
document.writeln("	  					<div>");
document.writeln("	  						<a href=\'index.html\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							ホーム");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  				</div>");
document.writeln("	  			</li>");
document.writeln("	  			<li class=\'pos-r\'>");
document.writeln("	  				<a href=\'about.html\'>ABOUT</a>");
document.writeln("					<div class=\'second\'>");
document.writeln("	  					<div>");
document.writeln("	  						<a href=\'about.html#about_1\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							代表挨拶");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a href=\'about.html#about_2\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							会社概要");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a href=\'about.html#about_3\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							会社理念");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a href=\'http://maps.google.co.jp/maps?f=q&source=s_q&hl=ja&geocode=&q=東京都新宿区高田馬場2-16-3柏ビル3F%0a&ie=UTF8\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							アクセス");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  				</div>");
document.writeln("	  			</li>");
document.writeln("	  			<li class=\'pos-r\'>");
document.writeln("	  				<a class=\'temp\'>OUR SERVICES</a>");
document.writeln("	  				<div class=\'second\'>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							不動産事業");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							環境事業");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							福祉事業");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							OEM事業");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							M&A事業");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							移民投資事業");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							旅行事業");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							健診・治療・美容事業");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  				</div>");
document.writeln("	  			</li>");
document.writeln("	  			<li class=\'pos-r\'>");
document.writeln("	  				<a class=\'temp\'>CONTACT</a>");
document.writeln("	  				<div class=\'second\'>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							お問い合わせ");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  				</div>");
document.writeln("	  			</li>");
document.writeln("	  			<li class=\'pos-r\'>");
document.writeln("	  				<a class=\'temp\'>JION US</a>");
document.writeln("	  				<div class=\'second\'>");
document.writeln("	  					<div>");
document.writeln("	  						<a class=\'temp\'>");
document.writeln("	  							<i class=\'icon-x_right a\'></i>");
document.writeln("	  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("	  							募集情報");
document.writeln("	  						</a>");
document.writeln("	  					</div>");
document.writeln("	  				</div>");
document.writeln("	  			</li>");
document.writeln("	  		</ul>");
document.writeln("  		</div>");
document.writeln("  		<div class=\'copyright text-center text-white\'>");
document.writeln("  			Copyright 2018© Goldenlight Trading Service All Rights Reserved");
document.writeln("  		</div>");
