    $(document).ready(function(){
      	$('.slider').bxSlider({
	      	auto:true,
	      	controls:false,
	      	pager:false,
	      	captions:false,
	    });
	    $(".menu").click(function(){
	    	$('.navListM').slideToggle();
	    });
	    $(".navListM li>a").click(function(){
	    	$(".navListM li .second").hide();
	    	$(this).next(".second").slideToggle();
	    })
	    $('a.temp').click(function(){
	    	$('.mask').show();
	    })
	    $('.maskClose').click(function(){
	    	$('.mask').hide();
	    })
    });




document.writeln("			<div class=\'nav pos-a top0 left0 right0 bottom0\'>");
document.writeln("				<div class=\'nav_bg pos-r\'>");
document.writeln("					<div class=\'logo_bg pos-r img-container pos-a\'></div>");
document.writeln("					<div class=\'logo pos-a text-center\'>");
document.writeln("						<img src=\'img/logo.png\' alt=\'\' />");
document.writeln("					</div>");
document.writeln("					<div class=\'nav_title paddingt30 pos-a float-left\'>");
document.writeln("						<img src=\'img/title-nav.png\' alt=\'\' />");
document.writeln("					</div>");
document.writeln("					<div class=\'menu pos-a right10 top10 dis-n\' style=\'z-index: 11\'>");
document.writeln("						<i class=\'icon-x_menu text-white\' style=\'font-size: 30px;\'></i>");
document.writeln("					</div>");
document.writeln("					<div class=\'navList float-right pos-r\'>");
document.writeln("				  		<ul class=\'clearfix\'>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a class=\'temp\'>HOME</a>");
document.writeln("				  				<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							ホーム");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a class=\'temp\'>ABOUT</a>");
document.writeln("								<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							代表挨拶");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							会社概要");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							会社理念");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							アクセス");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a class=\'temp\'>OUR SERVICES</a>");
document.writeln("				  				<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							不動産事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							環境事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							福祉事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							OEM事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							M&A事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							移民投資事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							旅行事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							健診・治療・美容事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a class=\'temp\'>CONTACT</a>");
document.writeln("				  				<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							お問い合わせ");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a class=\'temp\'>JION US</a>");
document.writeln("				  				<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							募集情報");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  		</ul>");
document.writeln("				  	</div>");
document.writeln("				  	<div class=\'navListM float-right pos-r\'>");
document.writeln("				  		<ul class=\'clearfix\'>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a>HOME</a>");
document.writeln("				  				<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							ホーム");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a>ABOUT</a>");
document.writeln("								<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							代表挨拶");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							会社概要");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							会社理念");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							アクセス");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a>OUR SERVICES</a>");
document.writeln("				  				<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							不動産事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							環境事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							福祉事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							OEM事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							M&A事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							移民投資事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							旅行事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							健診・治療・美容事業");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a>CONTACT</a>");
document.writeln("				  				<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							お問い合わせ");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  			<li class=\'pos-r\'>");
document.writeln("				  				<a>JION US</a>");
document.writeln("				  				<div class=\'second\'>");
document.writeln("				  					<div>");
document.writeln("				  						<a class=\'temp\'>");
document.writeln("				  							<i class=\'icon-x_right a\'></i>");
document.writeln("				  							<i class=\'icon-x_rightFill hover\'></i>");
document.writeln("				  							募集情報");
document.writeln("				  						</a>");
document.writeln("				  					</div>");
document.writeln("				  				</div>");
document.writeln("				  			</li>");
document.writeln("				  		</ul>");
document.writeln("				  	</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'pos-a bgTemp right0\'></div>");
document.writeln("			</div>");